DELETE http://localhost:8080/events/17
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hdGFuQGVtYWlsLmNvbSIsImV4cCI6MTc3NDI3Nzg5MCwidXNlcklkIjoxfQ.UVas2Qvalj-_97qidcjmp1X4SwQaJ4axG58QmkFV8P4